---
- name: create-compose-file | create docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "/dockerNginx/docker-compose.yml"
    mode: 0755

- name: create-compose-file | check contents
  shell: "cat /dockerNginx/docker-compose.yml"
  register: compose_file

- name: create-compose-file | display contents
  debug:
    var: compose_file.stdout_lines

- name: Docker Compose Down
  shell: 'docker rm -f $(docker ps -aq)'
  args:
    chdir: /dockerNginx
  ignore_errors: True
  register: compose_down

- debug:
    var: compose_down

- name: Build Docker Image
  shell: 'docker-compose -f /dockerNginx/docker-compose.yml build'
  args:
    chdir: /dockerNginx
  register: build

- debug:
    var: build

- name: Docker Compose Up
  shell: 'docker-compose -f /dockerNginx/docker-compose.yml up -d'
  args:
    chdir: /dockerNginx
  register: output

#- name: create-compose-file | Clean docker components (docker-compose down)
#  docker_compose:
#    project_src: "/dockerNginx"
#    state: absent
#    remove_images: local
#    remove_orphans: yes

#- name: create-compose-file | Create docker components (docker-compose up)
#  docker_compose:
#    project_src: "/dockerNginx"
#  register: createoutput

- debug:
    var: output
